// Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>

int main()
{
    long result{0}, fib_prev{0}, fib_curr{1}, aux;

    while (fib_curr <= 4000000)
    {
        aux = fib_curr + fib_prev;
        fib_prev = fib_curr;
        fib_curr = aux;
        if (!(aux % 2))
            result += aux;
    }

    std::cout << "Result: " << result << "\n";
}